// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetImageImageWorkIdPageNumGetData, GetImageImageWorkIdPageNumGetError, GetImageImageWorkIdPageNumGetResponse, GetAuthorsAuthorsGetError, GetAuthorsAuthorsGetResponse, GetAuthorAuthorAuthorIdGetData, GetAuthorAuthorAuthorIdGetError, GetAuthorAuthorAuthorIdGetResponse, GetWorkWorkWorkIdGetData, GetWorkWorkWorkIdGetError, GetWorkWorkWorkIdGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Image
 */
export const getImageImageWorkIdPageNumGet = <ThrowOnError extends boolean = false>(options: Options<GetImageImageWorkIdPageNumGetData, ThrowOnError>) => { return (options?.client ?? client).get<GetImageImageWorkIdPageNumGetResponse, GetImageImageWorkIdPageNumGetError, ThrowOnError>({
    ...options,
    url: '/image/{work_id}/{page_num}'
}); };

/**
 * Get Authors
 */
export const getAuthorsAuthorsGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetAuthorsAuthorsGetResponse, GetAuthorsAuthorsGetError, ThrowOnError>({
    ...options,
    url: '/authors'
}); };

/**
 * Get Author
 */
export const getAuthorAuthorAuthorIdGet = <ThrowOnError extends boolean = false>(options: Options<GetAuthorAuthorAuthorIdGetData, ThrowOnError>) => { return (options?.client ?? client).get<GetAuthorAuthorAuthorIdGetResponse, GetAuthorAuthorAuthorIdGetError, ThrowOnError>({
    ...options,
    url: '/author/{author_id}'
}); };

/**
 * Get Work
 */
export const getWorkWorkWorkIdGet = <ThrowOnError extends boolean = false>(options: Options<GetWorkWorkWorkIdGetData, ThrowOnError>) => { return (options?.client ?? client).get<GetWorkWorkWorkIdGetResponse, GetWorkWorkWorkIdGetError, ThrowOnError>({
    ...options,
    url: '/work/{work_id}'
}); };